### ISSUE TITLE
Unable to install Proxygen

### ISSUE THREAD

**Issue by vaibhav-kaushal** [facebook/proxygen#25]
I ran the commands as mentioned (run ```./deps.sh``` and then ```./reinstall.sh```) but the installation fails. Here are the last few lines of the make output: https://gist.github.com/vaibhav-kaushal/586b51257494d56e673a 

Basically it never gets out of that tests folder. Here is a screenshot:

![screenshot 2014-12-26 17 54 07](https://cloud.githubusercontent.com/assets/2824682/5557551/3c603794-8d29-11e4-8657-e6c29a771da7.png)

I have waited for more than an hour, nothing happened. I tried reinstalling the things again and again but fails every time. I have an Ubuntu updated 14.04 (desktop). What might be the problem here?

**Comment by vaibhav-kaushal** [comment]
Cool. Thanks! When is it expected to be pushed? I wanted to work on Proxygen and since the compilation process just gets stuck, I can't (I guess it is the testing phase where it gets stuck, but I'm clueless about how to use Proxygen from this state).

**Comment by port8080** [comment]
Fix has been pushed out. If you start with a clean checkout of the proxygen codebase, you should be able to run the compilation process to completion.

Sorry about that!

**Comment by vaibhav-kaushal** [comment]
And here is a new problem!

![screenshot 2015-01-08 14 25 28](https://cloud.githubusercontent.com/assets/2824682/5660123/694e6c44-9742-11e4-9f7b-ef6961212ef7.png)

**Comment by viswanathgs** [comment]
Could you paste the complete output?

**Comment by vaibhav-kaushal** [comment]
I am putting in the output which was available in the terminal (some output which was produced previously during compilation had scrolled past the terminal). 

http://pastebin.com/JNGsjitJ

**Comment by viswanathgs** [comment]
This is due to a missing dependency in github.com/facebook/folly. Fix for folly is on the way. I'll get back once we're good. Thanks!

**Comment by viswanathgs** [comment]
I just pushed a new version of https://github.com/facebook/folly to add the missing dependency. Could you stash your locally folly build and try recompiling proxygen?

**Comment by vaibhav-kaushal** [comment]
Nope, still does not work. Now it goes farther but fails with this: http://pastebin.com/V0yfhEHn

**Comment by vaibhav-kaushal** [comment]
Is it possible to make proxygen work without folly? (or thrift?). I am trying to implement a small HTTP server myself and would want to copy the code from proxygen. Since it is BSD code, I feel relatively free but I am not great with C++ right now.

**Comment by viswanathgs** [comment]
It turned out to be a dependency in fbthrift this time, and it's been fixed now. Sorry about that.
We should soon be independent of thrift, but proxygen libs very heavily relies on folly, so removing that dependency wouldn't be quite feasible.

**Comment by vaibhav-kaushal** [comment]
Thanks. I will try to recompile. 

And I do not like dependencies. So it’d be great to have thrift as an option! :)

**Comment by vaibhav-kaushal** [comment]
It compiled. reinstall.sh ran successfully as well. The message it shows after deps.sh complete is this: http://pastebin.com/d2UB6bsk <http://pastebin.com/d2UB6bsk> 

I think it’s done. I will proceed with testing. Just wanted to say - if you can, adding a message like “Compilation done, proceed with reinstall.sh” would be a good thing. 

Thanks for your immediate replies and help with this issue.

**Comment by viswanathgs** [comment]
Great, thanks for sticking with this!

**Comment by CipherLiu** [comment]
Have this issue fixed? why did I get the same problem with the code on master branch ?
